Repository PartooHub/developers-website, pull requests merged in 2021-03, with the labels that each got.

#123 [JT-453] - Details change before MEP
  rest_api/v2/tags/index.yml
Labels: jaguar-team

#124 [MEP] - Rework categories documentation - 03/03/2021
  rest_api/v2/components/index.yml
  rest_api/v2/paths/business/post_update.yml
  rest_api/v2/paths/category/get_search.yml
  rest_api/v2/tags/index.yml
Labels: documentation, jaguar-team

#126 Adding information for getMyUser
  rest_api/v2/components/index.yml
Labels: morty-team
