Repository PartooHub/developers-website, pull requests merged in 2021-02, with the labels that each got.

#106 [BPT] add warning in phone field
  rest_api/v2/components/index.yml
  rest_api/v2/paths/business/post_create.yml
  rest_api/v2/paths/business/post_update.yml
Labels: bird-person-team

#111 Add support section for Rest api
  Makefile
  README.md
  rest_api/v2/tags/index.yml
Labels: rick-team

#112 Add support page to the documentation REST
  Makefile
  README.md
  rest_api/v2/tags/index.yml
Labels: rick-team

#110 [BPT] add deprecated
  rest_api/v2/paths/business/post_create.yml
Labels: bird-person-team

#114 Consistent warning message on API breaking changes
  rest_api/v2/components/index.yml
  rest_api/v2/paths/authorize/get.yml
  rest_api/v2/paths/authorize/post.yml
  rest_api/v2/paths/authorize/post_revoke.yml
  rest_api/v2/paths/business/post_create.yml
  rest_api/v2/paths/category/get_search.yml
Labels: rick-team

#116 [BPT-1394] Add endpoints : /publisher_states/business_info & /publisher_states/businesses_info
  rest_api/v2/components/presence/parameters.yml
  rest_api/v2/components/presence/schemas.yml
  rest_api/v2/paths/index.yml
  rest_api/v2/paths/presence/get_business_info.yml
  rest_api/v2/paths/presence/get_businesses_info.yml
  rest_api/v2/tags/index.yml
Labels: bird-person-team

#118 [JT-277] - Change logs changed
  rest_api/v2/tags/changeLogs.yml
Labels: jaguar-team
